### ISSUE TITLE
KILLED problem

### ISSUE THREAD

**Issue by aytek03** [xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master#35]
Hi Sir,

When the hazelnut images come, kill problem is occured.

How do we solve "the kill" problem?

(resize=256, cropsize=224)

**Comment by JohnnyHopp** [comment]
Hi @aytek03 , if I remember correctly, I think it's OOM issue when calculating inverse matrix or pickle saving due to the large image number of hazelnut catetory. 

So you can try to save the parameter by replacing pickle format with hdf5 at first. If it doesn't work, you may have to increase you memory or smaller backbone model like EfficientNet.

I implemented an EfficientNetV2 based PaDiM with parameters saved in hdf5 format, you can have a look as a reference.
[PaDiM-EfficientNetV2](https://github.com/JohnnyHopp/PaDiM-EfficientNetV2)

**Comment by aytek03** [comment]
Hi @JohnnyHopp 
Thank you for your information. I will try it.
